apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: demo
      defaultBucket: vxg_tests
    secureJsonData:
      token: local-dev-token
    isDefault: true
